### ISSUE TITLE
a problem in running code

### ISSUE THREAD

**Issue by hoenza** [openai/sparse_attention#9]
When I tried to run the code the following error occurred:
Traceback (most recent call last):
  File "attention.py", line 4, in <module>
    from blocksparse import BlocksparseTransformer
  File "/home/user/anaconda3/lib/python3.7/site-packages/blocksparse/__init__.py", line 3, in <module>
    from blocksparse.utils import (
  File "/home/user/anaconda3/lib/python3.7/site-packages/blocksparse/utils.py", line 16, in <module>
    _op_module = tf.load_op_library(os.path.join(data_files_path, 'blocksparse_ops.so'))
  File "/home/en/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: libcudart.so.10.0: cannot open shared object file: No such file or directory

**Comment by dav-ell** [comment]
This looks like a CUDA installation issue, not an issue with this repo. I'd recommend making sure your installation is working, before using this repo, and then trying again.
